<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.gameframe</groupId>
    <artifactId>gameframe-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>game-transport-zfoo</artifactId>
  <dependencies>
    <dependency>
      <groupId>io.gameframe</groupId>
      <artifactId>game-runtime</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>io.gameframe</groupId>
      <artifactId>game-scene</artifactId>
      <version>0.1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk15on</artifactId>
      <version>1.59</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk15on</artifactId>
      <version>1.59</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.zfoo</groupId>
      <artifactId>net</artifactId>
      <version>${zfoo.version}</version>
    </dependency>
  </dependencies>
</project>